server {
  listen 8321;
  server_name test;
  error_page 404 /404.html;
  root /home/davmoren/Desktop/webserv/web/;
  index index.html;

  client_read_timeout 30;     # default, 0 = sin timeout

  location /directory {
    alias /home/davmoren/Desktop/webserv/YoupiBanane/;
    index youpi.bad_extension;
    autoindex on;
    allow_methods GET POST;
    cgi_path /home/davmoren/Desktop/webserv/cgi_test;
    cgi_ext .bla;
  }

  location /post_body {
    allow_methods POST;
    client_max_body_size 100;
  }
}

