server {
  listen 8321;
  server_name test;
  error_page 404 /404.html;
  root web/;
  index index.html;

  location /directory {
    alias YoupiBanane/;
    index youpi.bad_extension;
    autoindex on;
    allow_methods GET POST;
    cgi_path /home/mikel/Documents/webserv/cgi_test;
    cgi_ext .bla;
  }

  location /post_body {
    allow_methods POST;
    client_max_body_size 100;
  }
}
