server {
  listen 8321;
  server_name test;
  error_page 404 /404.html;
  root /home/mikel/Desktop/github/web/;
  index index.html;

  client_read_timeout 60;

  location /directory {
    alias /home/mikel/Desktop/github/YoupiBanane/;
    index youpi.bad_extension;
    autoindex on;
    allow_methods GET POST DELETE HEAD;
    cgi_path /home/mikel/Desktop/github/cgi_tester;
    cgi_ext .bla;
  }

  location /post_body {
    allow_methods POST;
    client_max_body_size 100;
  }

  location /cgi-bin {
      root /home/mikel/Desktop/github/web/cgi_bin;
      allow_methods GET POST DELETE HEAD;
      cgi_path /usr/bin/python3 /bin/bash;
      cgi_ext .py .sh;
  }

  location /uploads {
    root /home/mikel/Desktop/github/web/uploads;
    allow_methods GET POST DELETE;
    upload_store /home/mikel/Desktop/github/web/uploads;
    autoindex on;
  }

  location /old {
    return 301 /index.html;
  }
}

server {
  listen 8322;
  server_name segundo;
  root /home/mikel/Desktop/github/web2/;
  index index.html;
}
